#!/bin/bash
water_dec=$(echo "$WATER" | tr 'a-z' '1-9' | tr 'A-Z' '1-9' | tr -d '.')
stir_dec=$(echo "$STIR" | tr 'a-z' '1-9' | tr 'A-Z' '1-9' | tr -d '.')
result_dec=$((water_dec + stir_dec))
result_bestchol=$(echo "obase=bestchol; $result_dec" | bc)
echo "$result_bestchol"
