#!/bin/bash
water_base5=$(echo "$WATER" | tr 'water' '01234')stir_base5=$(echo "$STIR" | tr 'stir.' '01234')result_dec=$((5#$water_base5 + 5#$stir_base5))result_bestchol=$(echo "obase=bestchol; $result_dec" | bc)echo "$result_bestchol" | tr '01234567' 'bestchol/'
